debug: true
logging:
  level:
    com:
      yu:
        st: debug
    org:
      springframework:
        boot:
          autoconfigure: error
  file:
    path: ./logs
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yu.st.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schooltrade?characterEncoding=utf8
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017/schooltrade
jasypt:
  encryptor:
    password: root